### ISSUE TITLE
Develop a Site Map for Interactions with the App

### ISSUE THREAD

**Issue by cassininazir** [davidowproject/ui#1]
Review Lance's presentation (linked below) and produce a site map that includes the functionality described in the app as well as functionality that the UI team would like to include.

https://www.dropbox.com/sh/thhvshq04adlz96/AAAQ7N-A8hAQ7zuaCbDN3ZcDa?dl=0

**Comment by cassininazir** [comment]
Sample comment.

**Comment by cassininazir** [comment]
Red routes http://userfocus.co.uk/articles/prioritising-functions.html

**Comment by summersaylor** [comment]
I created a template for everyone to use on the Features & Pages document (in the UI folder). My idea is that each of you will fill out the template with the types of pages you want and the features that will be on those pages. Once everyone has filled out their own template on the Features & Pages doc, I will create a LucidChart that is shared - this will be our site map. I will start it with the pages most people agree on with the templates. Then we can all discuss, comment and edit that chart. 

Friday Night - Fill out template within the Features & Pages document
Monday Night - Comment on the Lucid Chart

**Comment by cassininazir** [comment]
You're off to a good start, UI team!

**Comment by summersaylor** [comment]
Below is the Site Map. There is a Red Routes Sheet in the shared UI folder. Team, go to that document and put together your list of most needed to least needed features at the bottom. 
![site map - new page](https://cloud.githubusercontent.com/assets/10950415/6358939/cd5cb44a-bc34-11e4-8c40-1dfcba2b0d96.png)
