### ISSUE TITLE
Develop sketches for splash screen/launch image

### ISSUE THREAD

**Issue by cassininazir** [davidowproject/ui#11]
Splash screen is the first image seen after a user opens the app. It is fullscreen, appears for a few seconds while the app is loading, and usually contains an image, logo and current version of the app. This should include the UT Dallas logo. 

Might be nice if the splash screen had a background colour that was consistent with the outdoor time. 

Examples
- https://www.pinterest.com/timoa/mobile-ui-splashscreens/
  -https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/LaunchImages.html 
- http://www.slideshare.net/PocketYourShop/43-inspiratationalsplasscreens
- http://inspired-ui.com/

**Comment by summersaylor** [comment]
Below is the splash screen. Its in UI Group/SplashScreenFinal.jpg @judyn 

![splash screen 2](https://cloud.githubusercontent.com/assets/10950415/7093024/74df9e1c-df7b-11e4-8f60-d4598f37fd92.jpg)

**Comment by summersaylor** [comment]
@kiraamin Can you make a landscape version too by this Friday, the 24th. Currently, the image above is used in both views, but gets squished in landscape.

**Comment by judyn** [comment]
@kiraamin, could you save the file as a .png?? thanks!!

**Comment by kiraamin** [comment]
@judyn Okay. These will be the final splash screen images. You can find it under UI Group > Final Splash Screen in the Drive as well. Thanks!

![splashscreenfinal_landscape](https://cloud.githubusercontent.com/assets/11038715/7299878/30af3842-e99e-11e4-965f-fa98c2cab88f.png)

![splashscreenfinal](https://cloud.githubusercontent.com/assets/11038715/7299895/418b19b0-e99e-11e4-82f3-4902ad6da1a7.png)

**Comment by cassininazir** [comment]
Kira,

Nicely done! Also include the original photo on Google Drive.

Cassini Nazir

Clinical Assistant Professor, Arts and Technology
The University of Texas at Dallas
