### ISSUE TITLE
Bio Pics for Website

### ISSUE THREAD

**Issue by summersaylor** [davidowproject/ui#15]
Cassini said we will be making a website about the app, our process, and it will include individual pics and short bios per person. Lina, I saw you were taking pictures last class. Can you get pictures of everyone for the bio pics?

**Comment by linamoon** [comment]
Yes, next class we can have photo sessions for everybody.

**Comment by summersaylor** [comment]
@dylanorgeron @geoffreyvillalba 
Next class Lina will be taking our pictures for the website bio section. Please let your teams know so they can do their makeup.

**Comment by linamoon** [comment]
@geoffreyvillalba can help me with photos, heard he's quite good!

**Comment by geoffreyvillalba** [comment]
I'm more than happy to help with the photos!

On Apr 9, 2015 7:40 PM, Lina Moon notifications@github.com wrote:
@geoffreyvillalba can help me with photos, heard he's quite good!

---

**Comment by judyn** [comment]
oh god
