### ISSUE TITLE
Keynote Presentation of ENTIIIIIIRE Process

### ISSUE THREAD

**Issue by summersaylor** [davidowproject/ui#17]
@jackiefn Jackie and I will work on sections for a presentation about the process. Jackie will compile Code team milestones (with descriptions and images) as well as the Sitemap to determine app functions, Mood Board to focus direction, and UI Kit to build out working theme and common elements (first 3 in UI milestone list). I will pull together Research team milestones (with descriptions and images) and the Wireframes & OnBoarding, App Icon, and Sitemap for website & choose Wordpress theme (last 3 in UI milestone list).

Compiled info and basic presentation should be ready for Tuesday class.

**Comment by judyn** [comment]
I added screenshots of all current screens to Google Drive under code > screenshots. 

I am aware that the nav in the list view needs to be resized, as well as the filters not being present in the tile view, will be working on that soon (hopefully!) 

Let me know what needs to be changed, thanks!

https://drive.google.com/folderview?id=0B43_sWDwqEqZfjdmLTZZcW9IZEgwZDdQVzlaRnJPWklfNGFRQTN4YVBHam5mWHJBWUJ1Umc&usp=sharing

**Comment by cassininazir** [comment]
The UT Dallas logo in splash_portrait.png appears to be squished (it appears to be longer than it should be). Could the original creator re-export with the logo appropriately sized?

Cassini Nazir

Clinical Assistant Professor, Arts and Technology
The University of Texas at Dallas

**Comment by summersaylor** [comment]
Below are my change suggestions,
- Capitalize the words "mixed media". 
- The magnifying glass (List View, Dark Theme) doesn't fit within the header bar. 
- One image is missing from the Gallery view - an empty box is there. 
- In the Twitter view, can we show the question from the art piece instead of the words "What's happening?" or in addition to them? I have this problem (forgetting the question/the prompt) when I am using the discussion board on the Blackboard phone app and its no bueno.
- What happened to the Map? I see its not in the menu options anymas.

**I like the menu & twitter bird switching sides btw.**

Here are my comments on the settings page.

![screen shot 2015-04-23 at 7 50 38 pm](https://cloud.githubusercontent.com/assets/10950415/7310609/a0737656-e9f4-11e4-8f83-259a31fc1f80.png)

**Comment by linamoon** [comment]
Don't know if this will be useful in the presentation, but here's the link to Lance's capstone website just in case: https://davidowproject.wordpress.com/

**Comment by summersaylor** [comment]
@cassininazir @jackiefn @jjdoyle2010 I uploaded the presentation dated 05012015 to the Drive in the UI Groups folder and Presentation Files folder. I also sent you three an email with the embed link. Currently in Slideshare, the presentation is labeled private, can only be embedded on the davidow.atec.io website, and cannot be downloaded. We can change these settings later if needed.
