### ISSUE TITLE
How Do People Learn About the App?

### ISSUE THREAD

**Issue by summersaylor** [davidowproject/ui#18]
@Monsmaster @trtyler CJ and Ryan - Create a doc in the Drive documenting how we will tell people about the app. Develop at least 4 different ideas, with supporting pics and text, to demonstrate them. This is due by next class.

**Comment by Monsmaster** [comment]
These are some of our sketches for how to inform people about the app.
https://drive.google.com/drive/folders/0B6Vhc_NXSgDZfmFuYkwtZ0ZiclJHVnF1di1mUmpXUVpYVGowUmdFdDZFU3ozX3pWak5CRGs/0B4Zkup2g59yjfkJ3T1NYdXZJSVhJTU1ZYnFoYjRvM2hIdldNV2N5c1VGYzlnSU1pTmZxb0k
![option 1](https://cloud.githubusercontent.com/assets/7736824/7380652/bc9d95ce-edc2-11e4-8832-9eb787c0f004.jpg)
![option 2](https://cloud.githubusercontent.com/assets/7736824/7380653/bc9dce0e-edc2-11e4-93c8-56ebb4971752.jpg)
![option 3](https://cloud.githubusercontent.com/assets/7736824/7380654/bca89352-edc2-11e4-81d2-e8bf2ad117ea.jpg)
![option 4](https://cloud.githubusercontent.com/assets/7736824/7380655/bca94496-edc2-11e4-9058-2cdead46440b.jpg)

**Comment by trtyler** [comment]
These are some ideas that I came up with.  The first is what it might look like as a promotional image on the main school website carousel.

![art info main page](https://cloud.githubusercontent.com/assets/10950424/7380891/4d312ab4-edc4-11e4-9047-00154f11dbaf.jpg)

The second is supposed to be arrows on the floor leading people to a piece of art with instructions on getting the app.

![banner and floor ideas](https://cloud.githubusercontent.com/assets/10950424/7380892/4d328198-edc4-11e4-83fa-ea99ecc59bdc.jpg)

Below is an idea I had to put a flyer inside the elevator where people have no choice but to stare at it while they wait.

![elevator flyer](https://cloud.githubusercontent.com/assets/10950424/7380893/4d32d008-edc4-11e4-8025-57e3db2adb5b.jpg)

Below is supposed to be what people might see on those outdoor promotional stands for events and such that are spread around campus all the time.

![outdoor add stand](https://cloud.githubusercontent.com/assets/10950424/7380894/4d3473d6-edc4-11e4-83d0-479d33096ffb.jpg)

These are a few extra ideas:
![image](https://cloud.githubusercontent.com/assets/10950424/7381326/e49f3172-edc7-11e4-83b3-8073d3d2928f.png)

**Comment by summersaylor** [comment]
If there are/were tv's set up throughout the ATEC building, a live view of the @UTDDavidow Twitter feed could be displayed with corresponding artworks. A 2 column view showing art and Twitter feed.
