### ISSUE TITLE
Gallery & List View Toggle Button

### ISSUE THREAD

**Issue by summersaylor** [davidowproject/ui#19]
@Monsmaster CJ - create a few iterations with colors and shapes of the Gallery button. I think the List View button is fine. This is due Friday, the 24th.

**Comment by Monsmaster** [comment]
Here are the updated List Views & Gallery Views
![gallery view day](https://cloud.githubusercontent.com/assets/7736824/7380634/99710248-edc2-11e4-87d6-a83c6321c7ea.png)
![gallery view night](https://cloud.githubusercontent.com/assets/7736824/7380635/9977418a-edc2-11e4-9689-c54985f69ca3.png)

![list view night](https://cloud.githubusercontent.com/assets/7736824/7380607/7c7b062a-edc2-11e4-9df7-68812113b4ce.png)
![list view day](https://cloud.githubusercontent.com/assets/7736824/7380608/7c7f0554-edc2-11e4-8269-9c0eb492061a.png)
