### ISSUE TITLE
Mood Board

### ISSUE THREAD

**Issue by summersaylor** [davidowproject/ui#3]
@trtyler and @kiraamin ,

Keep the Mood Board section organized. Comment on others entries and contribute good ideas!
https://dribbble.com/
https://www.behance.net/

**Comment by cassininazir** [comment]
More info on Mood Boards here
- http://www.creativebloq.com/graphic-design/mood-boards-812470

Style Tiles might be useful as well. 
- http://alistapart.com/article/style-tiles-and-how-they-work
- http://alistapart.com/article/style-tiles-and-how-they-work

**Comment by cassininazir** [comment]
Add a link to the Google Drive URL and then close.

**Comment by summersaylor** [comment]
Link to the Mood Board in the Google Drive. 

https://docs.google.com/presentation/d/1dMYSJe0eLkVySDTLLxN7yVMKQFiDyVfa68Al_aZSk1k/edit?usp=drive_web
