### ISSUE TITLE
iOS & Android UI Guidelines

### ISSUE THREAD

**Issue by summersaylor** [davidowproject/ui#4]
Jackie and Summer,
Find design patterns within iOS and Android apps. Pay attention to typeface, colors, and design patterns. 
http://uxarchive.com/
http://www.pttrns.com/
http://www.google.com/design/spec/material-design/introduction.html#
http://phonegap.com/

**Comment by cassininazir** [comment]
- [Apple iOS Human Interface Guideliens](https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/)
- [Android Interface Guidelines](https://developer.android.com/design/index.html)

**Comment by cassininazir** [comment]
Jackie, I think you've both completed this task. You may close when ready.
