### ISSUE TITLE
User Interface Kit

### ISSUE THREAD

**Issue by summersaylor** [davidowproject/ui#5]
@greyhound77 and Allie,

Make the first draft of the UI Kit - due when we get back from Spring Break. Have examples of screens showing text next to images, glyphs next to buttons, etc. Below is a link to BootStraps Flat UI you can reference. 
http://designmodo.github.io/Flat-UI/

Kit should include:
- Buttons (all button states: active, visited, etc)
- Input 
- Dropodwn
- Select 
- Tags
- Navigation
- Progress Bars and Slides
- Toolbar Navigation
- Checkboxes
- Radio Buttons
- Switches
- Type (h1-h6 and paragraph) 
- Colour
- Icons

Also a few examples of screens assembled with elements in the kit would be useful.

**Comment by summersaylor** [comment]
Below are the screen shots of the first UI kit. Both blue and yellow options are shown and original file can be found the in the Internet Studio/UI Group/UI Kit path.

![screen shot 2015-03-25 at 4 33 16 pm](https://cloud.githubusercontent.com/assets/10950415/6836012/ab06db7a-d30c-11e4-8a6c-49070a1d94e7.png)
![screen shot 2015-03-25 at 4 33 09 pm](https://cloud.githubusercontent.com/assets/10950415/6836013/ab0ee568-d30c-11e4-9785-6a225b0378a7.png)

**Comment by Monsmaster** [comment]
Icon Font is finished and can be located under the google drive UI Kit.  Here is the direct link to the Font.

https://drive.google.com/file/d/0B4Zkup2g59yjeGgxM1F4WlJ2MEU/view?usp=sharing
