### ISSUE TITLE
Create CSS(LESS) Package for UI Kit

### ISSUE THREAD

**Issue by cassininazir** [davidowproject/ui#6]
Now that you've created the first round UI kit in an imaging tool, create the CSS for your UI kit. 

The team should use LESS, a CSS preprocessor, for this. Although it will be slow going at first, you will greatly benefit from this. 

Review the pages at:
-  http://lesscss.org/
- http://lesscss.org/features/ 

Then have team members create an account in [CodePen](http://codepen.io/) and create forks of each other's work. Have started a _basic_ page at http://codepen.io/cassininazir/pen/vEbJKq.

**Comment by summersaylor** [comment]
Final files are uploaded in our code. They are davidow.html, stylesBlue.css, and stylesYellow.css.
