### ISSUE TITLE
Wireframing

### ISSUE THREAD

**Issue by summersaylor** [davidowproject/ui#7]
The code team has asked that we provide them some mock ups of the pages. To do this, we are going to draw out some low-fidelity wireframes, upload them into the Google Drive (under Wireframes) and then vote in a spread sheet. I will set up the spread sheet later, for now please contribute to the wireframes. You can look in the folder now to see examples. 

*_If you do not like to draw/can't draw/have no ideas, be sure to comment in the voting spread sheet on things you like and give critiques. I don't expect you to all draw one option for each page, but a few drawings per person will make this easy for everyone. 
*_Everyone needs to vote on all of the page options. 
**Please follow the naming convention of folder name + number 
EX: Home1, ArtInfo1, Gallery2, SM4

**Comment by cassininazir** [comment]
Glad to see this collab between code and ui team. Not everyone can draw [well], but everyone can sketch! Added a resource to the Google Drive > Resources > _Prototytyping - A Practictioners Guide_ that will help the team make better prototypes and wireframes.

**Comment by summersaylor** [comment]
Below are the final wireframes. 
![wire_frames2](https://cloud.githubusercontent.com/assets/10950415/7007204/3b745d1a-dc4d-11e4-9a03-73da84b362c0.jpg)

In the Drive (Wire_Frames2.jpg)- https://drive.google.com/drive/#folders/0B6Vhc_NXSgDZfjZzZlR2VUpiYmMtTEUteWNEdE93WlpkTTEzMnVuaHdGajYzNURpWnlPd0U/0B6Vhc_NXSgDZfmFuYkwtZ0ZiclJHVnF1di1mUmpXUVpYVGowUmdFdDZFU3ozX3pWak5CRGs/0B6Vhc_NXSgDZcTYtVUdNX0pmN1U/0B6Vhc_NXSgDZfmZTY2F6NG1jNlZkR1Y3SGhET3c2YURmRmZ1R3Y2WEJCWlR5d1RvMHlLTkE

**Comment by cassininazir** [comment]
Nicely done!

Cassini Nazir

Clinical Assistant Professor, Arts and Technology
The University of Texas at Dallas
