### ISSUE TITLE
Draft wireframes for onboarding

### ISSUE THREAD

**Issue by cassininazir** [davidowproject/ui#8]
Onboarding is the "tutorial" that pops up when you first open an app. See examples at http://uxarchive.com/tasks/onboarding

Create wireframes for onboarding. You might begin by:
1. Explain the collection
2. Explain the explore functionality
3. Explain the gallery functionality
4. Explain any social features 

This should be done through use of a graphic and very succinct text. We will work through this together in class.

**Comment by cassininazir** [comment]
Onboarding for Google translate is quite nice. The use of the hand holding the app explains how the app functions when in the environment. 

http://uxarchive.com/apps/google_translate

![94e2ed02b8e08e9cf7088fb46755ba929ddb0f8e](https://cloud.githubusercontent.com/assets/1661430/7026956/77ddd842-dd12-11e4-8b22-5467dac3da0a.png)

**Comment by summersaylor** [comment]
Final file can be found in the Drive at the link below. 

https://drive.google.com/drive/u/0/folders/0B6Vhc_NXSgDZfjZzZlR2VUpiYmMtTEUteWNEdE93WlpkTTEzMnVuaHdGajYzNURpWnlPd0U/0B6Vhc_NXSgDZfmFuYkwtZ0ZiclJHVnF1di1mUmpXUVpYVGowUmdFdDZFU3ozX3pWak5CRGs/0B6Vhc_NXSgDZcTYtVUdNX0pmN1U

![onboarding](https://cloud.githubusercontent.com/assets/10950415/7150433/8047a232-e2e0-11e4-9046-355b01bd5408.jpg)
